# Generated by Django 5.2.1 on 2025-05-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('visit_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=10)),
            ],
        ),
    ]
