# Generated by Django 5.2.1 on 2025-05-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_created_at_alter_payment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
