# Generated by Django 5.2.1 on 2025-05-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='time_slots',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='doctor',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='visits.doctor'),
            preserve_default=False,
        ),
    ]
