# Generated by Django 5.2.1 on 2025-05-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_remove_doctor_time_slots_remove_timeslot_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
    ]
