# Generated by Django 5.2.1 on 2025-05-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_alter_timeslot_doctor_alter_visit_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
