# Generated by Django 5.2.1 on 2025-05-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.doctor'),
        ),
    ]
