# Generated by Django 5.2.1 on 2025-05-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_alter_timeslot_doctor_alter_visit_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='variant',
            field=models.CharField(choices=[('first', 'First visit'), ('follow_up', 'Follow-up visit')], default='first', max_length=20),
        ),
    ]
