# Generated by Django 5.2.1 on 2025-05-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_visit_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='variant',
        ),
        migrations.AddField(
            model_name='doctor',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
            preserve_default=False,
        ),
    ]
