# Generated by Django 5.2.3 on 2025-06-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='timestamp',
            new_name='sent_at',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
